#!/usr/bin/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC2016

# Prevent writing of coredumps
#  - Reason for coredumps: https://github.com/mikenye/docker-radarbox/issues/9#issuecomment-633068833
#  - Changes to docker-compose.yml: https://github.com/mikenye/docker-radarbox/issues/10#issuecomment-634027861
ulimit -c 0

# Test sxfeeder can run natively (without qemu)
if /usr/bin/sxfeeder --no-start --version > /dev/null 2>&1; then
  # can be run natively
  if [ "$VERBOSE_LOGGING" == "true" ]; then
        /usr/bin/sxfeeder 2>&1 | \
            stdbuf -oL awk '{print "[sxfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    else
        /usr/bin/sxfeeder 2>&1 | \
            stdbuf -oL awk '! / Statistics updated every 60 seconds /' | \
            stdbuf -oL awk '! /Packets sent in the last 60 seconds: /' | \
            stdbuf -oL awk '! / Data sent: /' | \
            stdbuf -oL awk '! / Data received: /' | \
            stdbuf -oL awk '{print "[sxfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi
else
  # needs qemu 
  if [ "$VERBOSE_LOGGING" == "true" ]; then
        qemu-arm-static /usr/bin/sxfeeder 2>&1 | \
            stdbuf -oL awk '{print "[sxfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    else
        qemu-arm-static /usr/bin/sxfeeder 2>&1 | \
            stdbuf -oL awk '! / Statistics updated every 60 seconds /' | \
            stdbuf -oL awk '! /Packets sent in the last 60 seconds: /' | \
            stdbuf -oL awk '! / Data sent: /' | \
            stdbuf -oL awk '! / Data received: /' | \
            stdbuf -oL awk '{print "[sxfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi
fi
